sudo: required
services:
    - docker


before_install:
    - docker build -t leishen7/docker-react -f Dockerfile.dev .

scripts:
    - docker run leishen7/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-west-2-7777777777777777"
    bucket_path: "docker-react"
on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secure: "$AWS_SECRET_KEY"